"""
Turning a finished screening into a draft prescription.

The input is the `metricsJson` payload that PostureAnalysis, GaitAnalysis and
ROMAnalysis all store - one entry per metric carrying value, unit, status, normal range
and confidence. The output is a list of exercises with the reason each one is there,
written in language a patient can read.

Three gates stand between a number and a prescription, and each exists because
prescribing without it would be worse than prescribing nothing:

  1. **Status must be `measured`.** The pipeline distinguishes "we measured this and it
     is abnormal" from "we could not measure this". A metric that is
     `insufficient_data` because the patient never turned sideways is not a normal
     result, and treating a missing side view as a healthy shoulder would tell a
     patient with a frozen shoulder that nothing needs doing.

  2. **The metric must have a cited normal range.** Half the registry deliberately has
     none - either because the metric is a descriptive proportion with no clinical
     threshold, or because its measurement error is wider than the range anyone
     publishes. Without a range there is no "outside" to be on.

  3. **The deviation must exceed the metric's MDC95.** This is the gate that stops the
     product from prescribing noise. MDC95 is the smallest difference between two
     screenings of the same person that is distinguishable from measuring twice
     (app/core/metrics/repeatability.py). A pelvic obliquity 0.3 degrees outside a band
     whose MDC95 is 1.08 degrees is a measurement that landed on the other side of a
     line, not a finding, and a patient handed four exercises for it would be doing
     them for a number that will have moved on its own by next week.

A finding that fails gate 3 is still reported - the clinician sees it marked
`borderline` - but it prescribes nothing on its own.

What comes out is a DRAFT. See the note on PlanStatus in the Prisma schema: no patient
sees any of this until a clinician has.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

from app.core.exercise.library import (
    EXERCISES_BY_SLUG,
    BodyRegion,
    ExerciseDef,
    Rule,
    Side,
    Trigger,
    rules_for_metric,
)
from app.core.metrics.repeatability import mdc95_for

#: Bumped whenever the rules or the grading change, and stamped onto every plan. A plan
#: generated last month was generated by different logic, and saying so is cheaper than
#: pretending the output is stable.
ENGINE_VERSION = 1

#: Metrics whose normal range is a floor rather than a band: reaching further than the
#: range is healthy, falling short of it is the finding. Every range-of-motion metric
#: works this way, per the note at the top of app/core/metrics/rom_registry.py.
#: Recognised by prefix rather than listed, so a new ROM metric is covered on the day
#: it is added rather than on the day somebody remembers this list.
_FLOOR_PREFIXES = ("rom_",)

#: Gait metrics that are also floors - more is better, less is the finding - despite
#: being published as a band. Walking slower than the band is a finding; walking faster
#: is a healthy adult in a hurry.
_FLOOR_KEYS = frozenset(
    {
        "stride_length_ratio",
        "walking_speed_ratio",
        "knee_flexion_max",
        "hip_flexion_max",
    }
)

SEVERITY_ORDER = {"borderline": 0, "mild": 1, "moderate": 2, "marked": 3}


def _is_floor_metric(key: str) -> bool:
    return key in _FLOOR_KEYS or any(key.startswith(p) for p in _FLOOR_PREFIXES)


@dataclass
class Finding:
    """One metric that landed outside where it should be."""

    metric_key: str
    clinical_name: str
    value: float
    unit: str
    normal_range: Tuple[float, float]
    #: "below" or "above" - which side of the range the value fell on.
    direction: str
    #: How far outside, in the metric's own unit. Always positive.
    deviation: float
    severity: str
    #: Whether the deviation is bigger than this metric's minimal detectable change.
    #: None when the metric's repeatability has never been measured - in which case the
    #: finding is reported but flagged, rather than silently trusted or silently dropped.
    exceeds_mdc: Optional[bool]
    mdc95: Optional[float]
    #: False for a finding too small to distinguish from measurement noise. Such a
    #: finding never drives a prescription on its own.
    actionable: bool
    #: Plain-language statement, shown to the patient.
    statement: str
    side: str = "none"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "metricKey": self.metric_key,
            "clinicalName": self.clinical_name,
            "value": round(self.value, 3),
            "unit": self.unit,
            "normalRange": list(self.normal_range),
            "direction": self.direction,
            "deviation": round(self.deviation, 3),
            "severity": self.severity,
            "exceedsMdc": self.exceeds_mdc,
            "mdc95": self.mdc95,
            "actionable": self.actionable,
            "statement": self.statement,
            "side": self.side,
        }


@dataclass
class Prescription:
    """One exercise on the draft plan, with everything needed to justify it."""

    exercise_slug: str
    exercise: ExerciseDef
    priority: int
    severity: str
    reason: str
    trigger_metric_keys: List[str] = field(default_factory=list)
    sides: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "exerciseSlug": self.exercise_slug,
            "name": self.exercise.name,
            "bodyRegion": self.exercise.body_region.value,
            "difficulty": self.exercise.difficulty.value,
            "priority": self.priority,
            "severity": self.severity,
            "reason": self.reason,
            "triggerMetricKeys": list(self.trigger_metric_keys),
            "sides": list(self.sides),
            "sets": self.exercise.default_sets,
            "reps": self.exercise.default_reps,
            "holdSeconds": self.exercise.default_hold_seconds,
            "frequencyPerWeek": self.exercise.default_frequency_per_week,
        }


# ---------------------------------------------------------------------------
# Reading the stored payload
# ---------------------------------------------------------------------------


def _iter_metric_entries(metrics_json: Any) -> Iterable[Tuple[str, Dict[str, Any]]]:
    """
    Yield (key, entry) over whatever shape `metricsJson` arrived in.

    Posture and gait store `{"metrics": {key: {...}}, ...}`. ROM stores one payload per
    movement merged into a single `metrics` map, and older rows store the metrics map at
    the top level with no wrapper. All three are read here rather than in three callers,
    because a reader that only understands one shape returns "no findings" for the other
    two - which looks exactly like a healthy patient.
    """
    if not isinstance(metrics_json, dict):
        return

    container = metrics_json.get("metrics")
    if isinstance(container, dict):
        source = container
    else:
        # Top-level map of metric entries. Identified by the entries themselves rather
        # than by absence of a wrapper, so a payload with unrelated top-level keys does
        # not get read as if every one of them were a metric.
        source = {
            k: v
            for k, v in metrics_json.items()
            if isinstance(v, dict) and ("status" in v or "value" in v)
        }

    for key, entry in source.items():
        if isinstance(entry, dict):
            yield key, entry


def _normal_range(entry: Dict[str, Any]) -> Optional[Tuple[float, float]]:
    raw = entry.get("normalRange") or entry.get("normal_range")
    if not raw or len(raw) != 2:
        return None
    try:
        lo, hi = float(raw[0]), float(raw[1])
    except (TypeError, ValueError):
        return None
    return (lo, hi) if lo <= hi else (hi, lo)


def _severity_for(deviation: float, scale: float) -> str:
    """
    Grade how far outside a value sits, in units of the band's own width.

    Scaling by the band rather than by an absolute number of degrees is what makes one
    function work for a 5-degree posture band and a 35-degree range-of-motion floor.
    """
    if scale <= 0:
        return "mild"
    ratio = deviation / scale
    if ratio >= 2.5:
        return "marked"
    if ratio >= 1.0:
        return "moderate"
    return "mild"


def _side_from_key(key: str) -> str:
    if key.endswith("_left") or key.startswith("left_"):
        return "left"
    if key.endswith("_right") or key.startswith("right_"):
        return "right"
    return "none"


def _statement(
    clinical_name: str,
    value: float,
    unit: str,
    normal: Tuple[float, float],
    direction: str,
    is_floor: bool,
) -> str:
    """One sentence a patient can read, naming the number and what was expected."""
    unit_suffix = {
        "degrees": "°",
        "percent": "%",
        "seconds": " s",
        "steps_per_min": " steps/min",
    }.get(unit, "")
    shown = f"{value:.1f}{unit_suffix}" if unit_suffix else f"{value:.2f}"
    lo, hi = normal
    if is_floor:
        return (
            f"{clinical_name} measured {shown}, short of the {lo:.0f}{unit_suffix} "
            f"a typical adult reaches."
        )
    expected = (
        f"{lo:.1f}{unit_suffix} to {hi:.1f}{unit_suffix}"
        if unit_suffix
        else f"{lo:.2f} to {hi:.2f}"
    )
    word = "below" if direction == "below" else "above"
    return f"{clinical_name} measured {shown}, {word} the expected {expected}."


# ---------------------------------------------------------------------------
# Findings
# ---------------------------------------------------------------------------


def extract_findings(metrics_json: Any, analysis_type: str) -> List[Finding]:
    """
    Every metric in this screening that landed outside its cited normal range.

    Findings come back sorted worst first. Metrics that could not be measured, that
    have no normal range, or that landed inside it produce nothing - a screening in
    which everything is fine legitimately returns an empty list, and callers must treat
    that as a result rather than as a failure.
    """
    findings: List[Finding] = []

    for key, entry in _iter_metric_entries(metrics_json):
        # Gate 1: only a metric the pipeline actually measured.
        status = str(entry.get("status", "")).lower()
        if status != "measured":
            continue

        value = entry.get("value")
        if value is None:
            continue
        try:
            value = float(value)
        except (TypeError, ValueError):
            continue

        # Gate 2: only a metric with a cited range to be outside of.
        normal = _normal_range(entry)
        if normal is None:
            continue

        lo, hi = normal
        is_floor = _is_floor_metric(key)

        if is_floor:
            # A signed floor metric - cervical lateral flexion is the only one today -
            # is graded on how far it travelled, not on which way. Comparing a left
            # side-bend of -40 against a floor of -45 would read a near-full movement
            # as a restriction.
            travelled = abs(value) if lo < 0 <= hi else value
            floor = max(abs(lo), abs(hi)) if lo < 0 <= hi else lo
            if travelled >= floor:
                continue
            direction = "below"
            deviation = floor - travelled
            # A floor has no band width to scale by, so severity is graded against a
            # tenth of the floor itself. It must be a FRACTION of the floor rather than
            # a fixed number: the floors in this registry run from 1.1 (walking speed,
            # a dimensionless ratio) to 180 (shoulder flexion, degrees), and any
            # constant large enough to mean something in degrees grades every ratio
            # metric as mild no matter how far short it falls.
            scale = max(floor * 0.10, 1e-9)
            normal_for_report = (floor, max(abs(lo), abs(hi)))
        else:
            if lo <= value <= hi:
                continue
            direction = "below" if value < lo else "above"
            deviation = (lo - value) if value < lo else (value - hi)
            scale = max((hi - lo) / 2.0, 1e-9)
            normal_for_report = (lo, hi)

        # Gate 3: bigger than this metric's own measurement noise.
        mdc = mdc95_for(key)
        exceeds_mdc: Optional[bool] = None if mdc is None else deviation > mdc
        actionable = exceeds_mdc is not False

        severity = "borderline" if not actionable else _severity_for(deviation, scale)

        statement = _statement(
            str(entry.get("clinicalName") or entry.get("clinical_name") or key),
            value,
            str(entry.get("unit") or ""),
            normal_for_report,
            direction,
            is_floor,
        )
        if exceeds_mdc is False and mdc is not None:
            statement += (
                f" This is within the repeat-measurement error for this metric "
                f"(±{mdc:g}), so it is reported but not treated as a finding."
            )

        findings.append(
            Finding(
                metric_key=key,
                clinical_name=str(
                    entry.get("clinicalName") or entry.get("clinical_name") or key
                ),
                value=value,
                unit=str(entry.get("unit") or ""),
                normal_range=normal_for_report,
                direction=direction,
                deviation=deviation,
                severity=severity,
                exceeds_mdc=exceeds_mdc,
                mdc95=mdc,
                actionable=actionable,
                statement=statement,
                side=_side_from_key(key),
            )
        )

    findings.sort(
        key=lambda f: (SEVERITY_ORDER.get(f.severity, 0), f.deviation), reverse=True
    )
    return findings


# ---------------------------------------------------------------------------
# Prescription
# ---------------------------------------------------------------------------


def _rule_fires(rule: Rule, finding: Finding) -> bool:
    if rule.trigger is Trigger.BELOW_NORMAL and finding.direction != "below":
        return False
    if rule.trigger is Trigger.ABOVE_NORMAL and finding.direction != "above":
        return False
    if rule.sign is not None:
        # The rule cares which way a signed metric deviated. `direction` alone is not
        # enough: a value below a band that straddles zero can still be positive.
        actual = "positive" if finding.value >= 0 else "negative"
        if actual != rule.sign:
            return False
    return True


def build_prescription(
    findings: Sequence[Finding], analysis_type: str, *, max_exercises: int = 8
) -> List[Prescription]:
    """
    Rank the exercises this set of findings calls for.

    One exercise reached by several findings is listed once, carrying every reason -
    a patient handed "wall slides" three times with three explanations would reasonably
    conclude the report is broken. Its priority is the sum of the contributions, so an
    exercise that addresses three findings outranks one that addresses a single worse
    one, which is the right call for a home programme where adherence falls off after
    the first handful.

    Capped at `max_exercises` because a twenty-item home programme gets done by nobody.
    The cap is applied after ranking, so what survives is the highest-value work.
    """
    severity_points = {"marked": 30, "moderate": 20, "mild": 10, "borderline": 0}

    merged: Dict[str, Prescription] = {}

    for finding in findings:
        # A borderline finding is inside measurement noise. It is shown to the
        # clinician, and it prescribes nothing by itself.
        if not finding.actionable:
            continue

        for rule in rules_for_metric(finding.metric_key, analysis_type):
            if not _rule_fires(rule, finding):
                continue

            side = rule.side.value if rule.side is not Side.NONE else finding.side
            points = severity_points.get(finding.severity, 10) * max(rule.weight, 1)
            reason = f"{finding.statement} {rule.rationale}".strip()

            for slug in rule.exercises:
                exercise = EXERCISES_BY_SLUG.get(slug)
                if exercise is None or not slug:
                    # A typo'd slug is caught by library.validate_rules() in the test
                    # suite. Skipping here as well means a bad deploy drops one
                    # exercise rather than failing the whole screening.
                    continue

                existing = merged.get(slug)
                if existing is None:
                    merged[slug] = Prescription(
                        exercise_slug=slug,
                        exercise=exercise,
                        priority=points,
                        severity=finding.severity,
                        reason=reason,
                        trigger_metric_keys=[finding.metric_key],
                        sides=[side] if side != "none" else [],
                    )
                else:
                    existing.priority += points
                    if SEVERITY_ORDER.get(finding.severity, 0) > SEVERITY_ORDER.get(
                        existing.severity, 0
                    ):
                        existing.severity = finding.severity
                    if finding.metric_key not in existing.trigger_metric_keys:
                        existing.trigger_metric_keys.append(finding.metric_key)
                        existing.reason = f"{existing.reason}\n\n{reason}"
                    if side != "none" and side not in existing.sides:
                        existing.sides.append(side)

    ranked = sorted(
        merged.values(),
        key=lambda p: (p.priority, SEVERITY_ORDER.get(p.severity, 0), p.exercise_slug),
        reverse=True,
    )
    return ranked[:max_exercises]


def summarise_findings(findings: Sequence[Finding], analysis_type: str) -> str:
    """
    A paragraph a patient can read at the top of their plan.

    Deliberately says the honest thing when nothing was found, rather than inventing
    reassurance: this screening measured what it could measure, and within that, these
    were the results.
    """
    label = {"POSTURE": "posture", "GAIT": "walking", "ROM": "joint range"}.get(
        analysis_type.upper(), "screening"
    )
    actionable = [f for f in findings if f.actionable]
    borderline = [f for f in findings if not f.actionable]

    if not actionable:
        base = (
            f"Your {label} screening did not find any measurement outside its expected "
            f"range."
        )
        if borderline:
            base += (
                f" {len(borderline)} measurement(s) sat just outside, by less than this "
                f"system can reliably distinguish from measurement error, so they are "
                f"listed for your clinician but not acted on."
            )
        return base

    worst = actionable[0]
    counts = {}
    for f in actionable:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    parts = [
        f"{n} {sev}" for sev, n in sorted(counts.items(), key=lambda kv: -SEVERITY_ORDER.get(kv[0], 0))
    ]
    return (
        f"Your {label} screening found {len(actionable)} measurement(s) outside their "
        f"expected range ({', '.join(parts)}). The most significant was: {worst.statement} "
        f"The exercises below were selected to address what was found, and your "
        f"clinician reviews them before they become your programme."
    )


def plan_title(analysis_type: str) -> str:
    return {
        "POSTURE": "Posture screening exercise programme",
        "GAIT": "Walking screening exercise programme",
        "ROM": "Joint range exercise programme",
    }.get(analysis_type.upper(), "Exercise programme")


def generate(metrics_json: Any, analysis_type: str, *, max_exercises: int = 8) -> Dict[str, Any]:
    """
    One call from a stored analysis to everything needed to write a draft plan.

    Returns a plain dict rather than model objects so the API layer can persist it and
    the report layer can render it without either importing the other.
    """
    findings = extract_findings(metrics_json, analysis_type)
    prescriptions = build_prescription(
        findings, analysis_type, max_exercises=max_exercises
    )
    return {
        "engineVersion": ENGINE_VERSION,
        "analysisType": analysis_type.upper(),
        "title": plan_title(analysis_type),
        "summary": summarise_findings(findings, analysis_type),
        "findings": [f.to_dict() for f in findings],
        "prescriptions": [p.to_dict() for p in prescriptions],
    }
