import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import type { AnalysisType } from '../../types/consultation';
import { getSuggestions } from '../../api/exercises';
import { useIsStaff } from '../../store/authStore';
import ExerciseCard from './ExerciseCard';

export interface SuggestedExercisesProps {
  analysisType: AnalysisType;
  analysisId: string;
  /** Renders on a dark report page; switches the panel chrome to match. */
  dark?: boolean;
}

/**
 * The exercises a screening suggests, shown at the bottom of every report.
 *
 * Mounted on the posture, gait and range-of-motion reports alike - the engine reads the
 * same metric payload from all three, so one component covers them.
 *
 * The wording is the careful part. What this panel shows is a *suggestion* generated by
 * rules over measurements, and it says so; what a patient is meant to do is their
 * clinician's prescription, which appears under "My plan" once reviewed. Presenting the
 * two as the same thing would be presenting an algorithm as clinical advice.
 */
export function SuggestedExercises({
  analysisType,
  analysisId,
  dark = false,
}: SuggestedExercisesProps) {
  const isStaff = useIsStaff();

  const { data, isLoading, isError, error } = useQuery({
    queryKey: ['exercise-suggestions', analysisType, analysisId],
    queryFn: () => getSuggestions(analysisType, analysisId),
    enabled: Boolean(analysisId),
    staleTime: 5 * 60 * 1000,
  });

  const panel: React.CSSProperties = {
    background: dark ? 'rgba(255,255,255,0.03)' : '#fff',
    border: dark ? '1px solid rgba(255,255,255,0.08)' : '1px solid #e2e8f0',
    borderRadius: 12,
    padding: 18,
    display: 'grid',
    gap: 14,
  };
  const heading = dark ? '#f1f5f9' : '#0f172a';
  const body = dark ? '#94a3b8' : '#475569';

  if (isLoading) {
    return (
      <section style={panel}>
        <p style={{ color: body, fontSize: 14, margin: 0 }}>
          Working out which exercises this screening suggests…
        </p>
      </section>
    );
  }

  if (isError) {
    return (
      <section style={panel}>
        <h2 style={{ color: heading, fontSize: 16, margin: 0 }}>Suggested exercises</h2>
        <p style={{ color: body, fontSize: 13, margin: 0 }}>
          {error instanceof Error
            ? error.message
            : 'Could not load exercise suggestions for this screening.'}
        </p>
      </section>
    );
  }

  if (!data) return null;

  const { prescriptions, summary, findings, plan } = data;
  const borderlineCount = findings.filter((finding) => !finding.actionable).length;

  return (
    <section style={panel}>
      <header style={{ display: 'grid', gap: 6 }}>
        <h2 style={{ color: heading, fontSize: 16, margin: 0 }}>Suggested exercises</h2>
        <p style={{ color: body, fontSize: 13, margin: 0, lineHeight: 1.6 }}>{summary}</p>
      </header>

      {prescriptions.length === 0 ? (
        <div
          style={{
            background: dark ? 'rgba(4,120,87,0.12)' : '#f0fdf4',
            border: dark ? '1px solid rgba(110,231,183,0.3)' : '1px solid #bbf7d0',
            borderRadius: 10,
            padding: '12px 14px',
          }}
        >
          <p
            style={{
              color: dark ? '#6ee7b7' : '#166534',
              fontSize: 13,
              margin: 0,
            }}
          >
            Nothing in this screening calls for a specific exercise. That is a result, not
            a gap - every measurement the capture could make sat inside its expected
            range.
          </p>
          {borderlineCount > 0 && (
            <p
              style={{
                color: dark ? '#5eead4' : '#15803d',
                fontSize: 12,
                margin: '6px 0 0',
              }}
            >
              {borderlineCount} measurement{borderlineCount === 1 ? '' : 's'} sat just
              outside, by less than this system can reliably distinguish from measurement
              error. Your clinician can see those.
            </p>
          )}
        </div>
      ) : (
        <>
          <p
            style={{
              background: dark ? 'rgba(59,130,246,0.1)' : '#eff6ff',
              border: dark ? '1px solid rgba(147,197,253,0.3)' : '1px solid #bfdbfe',
              borderRadius: 10,
              color: dark ? '#bfdbfe' : '#1e40af',
              fontSize: 12,
              lineHeight: 1.6,
              margin: 0,
              padding: '10px 12px',
            }}
          >
            {plan?.status === 'ACTIVE' ? (
              <>
                Your clinician has reviewed these and they are now your programme.{' '}
                <Link
                  to={`/my-plan/${plan.id}`}
                  style={{ color: dark ? '#93c5fd' : '#1d4ed8', fontWeight: 600 }}
                >
                  Open my plan
                </Link>
                .
              </>
            ) : (
              <>
                These are suggestions worked out from your measurements, not a
                prescription. Your clinician reviews them and decides what you should
                actually do - the reviewed version appears under <strong>My plan</strong>.
              </>
            )}
          </p>

          <div style={{ display: 'grid', gap: 10 }}>
            {prescriptions.map((suggestion) => (
              <ExerciseCard
                key={suggestion.exerciseSlug}
                exercise={
                  suggestion.exercise ?? {
                    id: null,
                    slug: suggestion.exerciseSlug,
                    name: suggestion.name,
                    bodyRegion: suggestion.bodyRegion,
                    difficulty: suggestion.difficulty,
                    equipment: [],
                    instructions: [],
                  }
                }
                dose={{
                  sets: suggestion.sets,
                  reps: suggestion.reps,
                  holdSeconds: suggestion.holdSeconds,
                  frequencyPerWeek: suggestion.frequencyPerWeek,
                }}
                reason={suggestion.reason}
                severity={suggestion.severity}
                sides={suggestion.sides}
              />
            ))}
          </div>
        </>
      )}

      {isStaff && plan && (
        <Link
          to={`/clinician/plans/${plan.id}`}
          style={{
            justifySelf: 'start',
            background: '#0e7490',
            borderRadius: 8,
            color: '#fff',
            fontSize: 13,
            fontWeight: 600,
            padding: '9px 16px',
            textDecoration: 'none',
          }}
        >
          {plan.status === 'DRAFT' ? 'Review and prescribe' : 'Open plan'}
        </Link>
      )}
    </section>
  );
}

export default SuggestedExercises;
